spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME:loan_decisioning}
    username: ${DB_USER:loan_app}
    password: ${DB_PASSWORD:loan_app}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:loan_app}
    password: ${RABBITMQ_PASSWORD:loan_app}
